export const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_USER_DATA: "SET_USER_DATA",
  USER_REGISTER_DATA: "USER_REGISTER_DATA",
  REGISTER_OTP: "REGISTER_OTP_VERIFY",
  SET_REGISTER_OTP: "SET_REGISTER_OTP",
  FORGOT_PASSWORD_OTP: "FORGOT_PASSWORD_OTP",
  SET_FORGOT_PASSWORD_OTP: "SET_FORGOT_PASSWORD_OTP",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  SET_FORGOT_PASSWORD: "SET_FORGOT_PASSWORD",
  RECOVER_PASSWORD: "RECOVER_PASSWORD",
  SET_RECOVER_PASSWORD: "SET_RECOVER_PASSWORD"
};
