export const actionTypes = {
	LOGIN: "LOGIN",
	REGISTER: "REGISTER",
	SET_LOADING: "SET_LOADING",
	SET_ERROR: "SET_ERROR",
	SET_USER_DATA: "SET_USER_DATA",
	USER_REGISTER_DATA: "USER_REGISTER_DATA"
};