export const dummyData = [
  {
    id: 1,
    name: 'Zahid Saeed',
    caseNumber: '1234',
    description: 'this is issue',
    time: 'time',
  },
  {
    id: 2,
    name: 'Noman Tahir',
    caseNumber: '324',
    description: 'You are great ',
    time: 'time',
  },
  {
    id: 3,
    name: 'Shahid Ali',
    caseNumber: '6573',
    description: 'Second One ',
    time: 'time',
  },
  {
    id: 3,
    name: 'Shahid Ali',
    caseNumber: '6573',
    description: 'Third one One ',
    time: 'time',
  },
  {
    id: 4,
    name: 'Shahid Ali',
    caseNumber: '6573',
    description: 'Third one One ',
    time: 'time',
  },
  {
    id: 5,
    name: 'Shahid Ali',
    caseNumber: '6573',
    description: 'Third one One ',
    time: 'time',
  },
  {
    id: 6,
    name: 'Shahid Ali',
    caseNumber: '6573',
    description: 'Third one One ',
    time: 'time',
  },
  {
    id: 7,
    name: 'Shahid Ali',
    caseNumber: '6573',
    description: 'Third one One ',
    time: 'time',
  },
];
